### ISSUE TITLE
Missing from opentelemetry.instrumentation.aiohttp_ Client

### ISSUE THREAD

**Issue by dreamnyj** [twocucao/tifa#33]
Missing from opentelemetry.instrumentation.aiohttp_ Client import aiohttpclientinstrumentor a file
你好，下拉了项目，总算把七七八八的依赖下载差不多。调试的话，提示缺少这个，能否给予指导。

**Comment by twocucao** [comment]
@dreamnyj opentelemetry.instrumentatiion 似乎并不是一个稳定的包. 你可以翻看一下文档哈.
